
apiVersion: v1
kind: Namespace
metadata:
  name: fruits-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: fruits-ns
type: Opaque
data:
  password: cG9zdGdyZXM=  # "postgres" base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fruits-ns
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fruits-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_DB
              value: fruitsdb
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fruits-ns
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-api
  namespace: fruits-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fruits-api
  template:
    metadata:
      labels:
        app: fruits-api
    spec:
      containers:
        - name: fruits-api
          image: YOUR_DOCKER_IMAGE
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              value: fruitsdb
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fruits-api
  namespace: fruits-ns
spec:
  selector:
    app: fruits-api
  ports:
    - port: 80
      targetPort: 3000
