---
apiVersion: v1
kind: Secret
metadata:
  name: fruits-db-secret
  namespace: edygc1988-dev
type: Opaque
data:
  password: cG9zdGdyZXM=  # "postgres" en base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fruits-postgres-pvc
  namespace: edygc1988-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-postgres
  namespace: edygc1988-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruits-postgres
  template:
    metadata:
      labels:
        app: fruits-postgres
    spec:
      # SIN securityContext - OpenShift asigna automáticamente
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fruits-db-secret
                  key: password
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: fruitsdb
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -d fruitsdb
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -d fruitsdb
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: fruits-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fruits-postgres
  namespace: edygc1988-dev
spec:
  type: ClusterIP
  selector:
    app: fruits-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-api
  namespace: edygc1988-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fruits-api
  template:
    metadata:
      labels:
        app: fruits-api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z fruits-postgres 5432; do
                echo "Esperando a PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL está listo"
      containers:
        - name: fruits-api
          image: edygc1988/fruits-api:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: fruits-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fruits-db-secret
                  key: password
            - name: DB_NAME
              value: fruitsdb
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fruits-api
  namespace: edygc1988-dev
spec:
  type: ClusterIP
  selector:
    app: fruits-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fruits-api-route
  namespace: edygc1988-dev
spec:
  to:
    kind: Service
    name: fruits-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect